module Cell {
  interface TubeCallback {
    void sendSMS (in string fromNum, in string message);
    string getNum();
    void blocked ();
  };

  interface Station {
    void register (in TubeCallback objRef, in string phoneNum);
    long registerStation(in Station objRef, in string stationName);
    long setStation(in Station objRef, in string stationName);
    void sendSMS (in string fromNum, in string toNum, in string message, in string ttl);
  };

};
