package Cell;


/**
* Cell/StationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* 27 декабря 2015 г. 22:02:17 MSK
*/

public interface StationOperations 
{
  void register (Cell.TubeCallback objRef, String phoneNum);
  void sendSMS (String fromNum, String toNum, String message);
} // interface StationOperations
