package Cell;


/**
* Cell/StationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* 28 декабря 2015 г. 15:46:46 MSK
*/

public interface StationOperations 
{
  void register (Cell.TubeCallback objRef, String phoneNum);
  int registerStation (Cell.Station objRef, String stationName);
  int setStation (Cell.Station objRef, String stationName);
  void sendSMS (String fromNum, String toNum, String message, String ttl);
} // interface StationOperations
