package Cell;


/**
* Cell/TubeCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* 28 декабря 2015 г. 15:46:46 MSK
*/

public interface TubeCallbackOperations 
{
  void sendSMS (String fromNum, String message);
  String getNum ();
  void blocked ();
} // interface TubeCallbackOperations
