package Cell;


/**
* Cell/TubeCallback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* 28 декабря 2015 г. 15:46:46 MSK
*/

public interface TubeCallback extends TubeCallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface TubeCallback
